### ISSUE TITLE
IndexError on Disambiguation page

### ISSUE THREAD

**Issue by howieweiner** [barrust/Wikipedia#10]
Hi. I started using this library this evening, and immediately ran into an IndexError here:
https://github.com/barrust/Wikipedia/blob/master/wikipedia/wikipedia.py#L724

The issue is easy to recreate with the following API call:

`page = wikipedia.page('Oasis')`

**Comment by barrust** [comment]
@howieweiner Thank you for pointing this out. I am actually not maintaining this code anymore as the original author has started to maintain his project again. I have actually done a complete re-write to better support changing MediaWiki sites. I would recommend using that library: [pymediawiki](https://github.com/barrust/mediawiki) 

This error also affected pymediawiki and a fix has been released for that library. So thank you! 

If you are interested in how to fix this in this library see below.

The fix is to change this code 
``` python
disambiguation = list()
for lis_item in filtered_lis:
    one_disambiguation = dict()
    item = lis_item.find_all("a")[0]
    if item:
        one_disambiguation["title"] = item["title"]
        one_disambiguation["description"] = lis_item.text
        disambiguation.append(one_disambiguation)
```
to 
``` python
disambiguation = list()
for lis_item in filtered_lis:
    item = lis_item.find_all('a')
    one_disambiguation = dict()
    one_disambiguation['description'] = lis_item.text
    if item:
         one_disambiguation['title'] = item[0]['title']
    else:
        # these are non-linked records so double up the text
        one_disambiguation['title'] = lis_item.text
    disambiguation.append(one_disambiguation)
```

**Comment by howieweiner** [comment]
Hi. Thanks for the update regarding this branch. Feel free to close this issue

**Comment by barrust** [comment]
@howieweiner will do and thank you for reporting this issue!
